### ISSUE TITLE
Project Crashing On Startup

### ISSUE THREAD

**Issue by wxy-ta** [tommybazar/TBRaymarcherPlugin#6]
hi ! I'm sorry to bother you. I'd like to ask you some questions.The project crashing on startup.I read through the crash logs and this it what I found:

Not using cached read wrapper
Started task graph with 5 named threads and 26 total threads with 3 sets of task threads.
Stats thread started at 0.186489
ICU TimeZone Detection - Raw Offset: +8:00, Platform Override: ''
Loading text-based GConfig....
Mounting plugin MeshPainting
Mounting plugin XGEController
Mounting plugin Paper2D
Mounting plugin EnvironmentQueryEditor
Mounting plugin AISupport
Mounting plugin LiveLink
Mounting plugin LightPropagationVolume
Mounting plugin OodleData
Mounting plugin OodleNetwork
Mounting plugin CameraShakePreviewer
Mounting plugin GameplayCameras
Mounting plugin AnimationSharing
Mounting plugin CodeLiteSourceCodeAccess
Mounting plugin CLionSourceCodeAccess
Mounting plugin GitSourceControl
Mounting plugin KDevelopSourceCodeAccess
Mounting plugin PixWinPlugin
Mounting plugin PerforceSourceControl
Mounting plugin PlasticSourceControl
Mounting plugin PluginUtils
Mounting plugin PropertyAccessNode
Mounting plugin RiderSourceCodeAccess
Mounting plugin NullSourceCodeAccess
Mounting plugin TextureFormatOodle
Mounting plugin SubversionSourceControl
Mounting plugin UObjectPlugin
Mounting plugin VisualStudioCodeSourceCodeAccess
Mounting plugin VisualStudioSourceCodeAccess
Mounting plugin XCodeSourceCodeAccess
Mounting plugin Niagara
Mounting plugin AssetManagerEditor
Mounting plugin CryptoKeys
Mounting plugin CurveEditorTools
Mounting plugin DataValidation
Mounting plugin GameplayTagsEditor
Mounting plugin GeometryMode
Mounting plugin FacialAnimation
Mounting plugin MacGraphicsSwitching
Mounting plugin MaterialAnalyzer
Mounting plugin MobileLauncherProfileWizard
Mounting plugin PluginBrowser
Mounting plugin SpeedTreeImporter
Mounting plugin DatasmithContent
Mounting plugin VariantManagerContent
Mounting plugin LuminPlatformFeatures
Mounting plugin MagicLeap
Mounting plugin MagicLeapLightEstimation
Mounting plugin MagicLeapMedia
Mounting plugin MagicLeapPassableWorld
Mounting plugin MLSDK
Mounting plugin AlembicImporter
Mounting plugin AutomationUtils
Mounting plugin BackChannel
Mounting plugin ChaosCloth
Mounting plugin ChaosClothEditor
Mounting plugin ChaosEditor
Mounting plugin ChaosSolverPlugin
Mounting plugin ChaosNiagara
Mounting plugin CharacterAI
Mounting plugin GeometryCache
Mounting plugin GeometryCollectionPlugin
Mounting plugin GeometryProcessing
Mounting plugin MotoSynth
Mounting plugin OpenImageDenoise
Mounting plugin PlanarCut
Mounting plugin ProxyLODPlugin
Mounting plugin PlatformCrypto
Mounting plugin PythonScriptPlugin
Mounting plugin SkeletalReduction
Mounting plugin AndroidMedia
Mounting plugin AvfMedia
Mounting plugin ImgMedia
Mounting plugin MediaCompositing
Mounting plugin MediaPlayerEditor
Mounting plugin WebMMedia
Mounting plugin WmfMedia
Mounting plugin TcpMessaging
Mounting plugin UdpMessaging
Mounting plugin ActorSequence
Mounting plugin LevelSequenceEditor
Mounting plugin MatineeToLevelSequence
Mounting plugin TemplateSequence
Mounting plugin OnlineSubsystem
Mounting plugin OnlineSubsystemNull
Mounting plugin OnlineSubsystemUtils
Mounting plugin LauncherChunkInstaller
Mounting plugin ActorLayerUtilities
Mounting plugin AndroidMoviePlayer
Mounting plugin AndroidDeviceProfileSelector
Mounting plugin AndroidPermission
Mounting plugin ScreenshotTools
Mounting plugin AppleImageUtils
Mounting plugin AppleMoviePlayer
Mounting plugin ArchVisCharacter
Mounting plugin AssetTags
Mounting plugin AudioCapture
Mounting plugin AudioSynesthesia
Mounting plugin CableComponent
Mounting plugin ChunkDownloader
Mounting plugin CustomMeshComponent
Mounting plugin EditableMesh
Mounting plugin ExampleDeviceProfileSelector
Mounting plugin GoogleCloudMessaging
Mounting plugin GooglePAD
Mounting plugin Takes
Mounting plugin HoudiniEngine
Mounting plugin IOSDeviceProfileSelector
Mounting plugin LocationServicesBPLibrary
Mounting plugin LinuxDeviceProfileSelector
Mounting plugin MobilePatchingUtils
Mounting plugin OpenXR
Mounting plugin OpenXREyeTracker
Mounting plugin OpenXRHandTracking
Mounting plugin PhysXVehicles
Mounting plugin PostSplashScreen
Mounting plugin ProceduralMeshComponent
Mounting plugin PropertyAccessEditor
Mounting plugin RuntimePhysXCooking
Mounting plugin SignificanceManager
Mounting plugin SoundFields
Mounting plugin Synthesis
Mounting plugin WebMMoviePlayer
Mounting plugin WindowsMoviePlayer
Mounting plugin ContentBrowserAssetDataSource
Mounting plugin ContentBrowserClassDataSource
Mounting plugin ContentBrowserFileDataSource
Mounting plugin OnlineSubsystemGooglePlay
Mounting plugin OnlineSubsystemIOS
Mounting plugin OculusVR
Mounting plugin TBRaymarcherPlugin
Incompatible or missing module: TBRaymarchProject
Incompatible or missing module: Raymarcher
Incompatible or missing module: FractalMarcher
Incompatible or missing module: VolumeTextureToolkit
Incompatible or missing module: VolumeTextureToolkitEditor
Incompatible or missing module: RayUtils
Running D:/UE4.27/UE_4.27/Engine/Binaries/DotNET/UnrealBuildTool.exe Development Win64 -Project="D:/bishe/TBRaymarchProject-master/TBRaymarchProject.uproject" -TargetType=Editor -Progress -NoEngineChanges -NoHotReloadFromIDE
Creating makefile for TBRaymarchProjectEditor (no existing makefile)
Houdini Engine : Found Houdini in C:/Program Files/Side Effects Software/Houdini 19.0.383
@progress push 5%
Parsing headers for TBRaymarchProjectEditor
  Running UnrealHeaderTool "D:\bishe\TBRaymarchProject-master\TBRaymarchProject.uproject" "D:\bishe\TBRaymarchProject-master\Intermediate\Build\Win64\TBRaymarchProjectEditor\Development\TBRaymarchProjectEditor.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -abslog="C:\Users\Admin\AppData\Local\UnrealBuildTool\Log_UHT.txt" -installed
LogInit: Display: Loading text-based GConfig....
Reflection code generated for TBRaymarchProjectEditor in 9.2633654 seconds
@progress pop
Building TBRaymarchProjectEditor...
Using Visual Studio 2019 14.29.30037 toolchain (C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037) and Windows 10.0.19041.0 SDK (C:\Program Files (x86)\Windows Kits\10).
Building 35 actions with 8 processes...
  @progress 'Compiling C++ source code...' 0%
  @progress 'Compiling C++ source code...' 3%
  [1/35] Default.rc2
  @progress 'Compiling C++ source code...' 6%
  [2/35] Default.rc2
  @progress 'Compiling C++ source code...' 9%
  [3/35] Default.rc2
  @progress 'Compiling C++ source code...' 11%
  [4/35] Default.rc2
  @progress 'Compiling C++ source code...' 14%
  [5/35] Default.rc2
  @progress 'Compiling C++ source code...' 17%
  [6/35] Default.rc2
  @progress 'Compiling C++ source code...' 20%
  [7/35] SharedPCH.UnrealEd.ShadowErrors.Cpp17.cpp
  @progress 'Compiling C++ source code...' 23%
  [8/35] SharedPCH.Engine.ShadowErrors.cpp
  @progress 'Compiling C++ source code...' 26%
  [9/35] Module.VolumeTextureToolkitEditor.gen.cpp
  @progress 'Compiling C++ source code...' 29%
  [10/35] Module.VolumeTextureToolkitEditor.cpp
  @progress 'Compiling C++ source code...' 31%
  [11/35] UE4Editor-VolumeTextureToolkitEditor.lib
    ???ڴ????? D:\bishe\TBRaymarchProject-master\Plugins\Raymarcher\Intermediate\Build\Win64\UE4Editor\Development\VolumeTextureToolkitEditor\UE4Editor-VolumeTextureToolkitEditor.lib ?Ͷ??? D:\bishe\TBRaymarchProject-master\Plugins\Raymarcher\Intermediate\Build\Win64\UE4Editor\Development\VolumeTextureToolkitEditor\UE4Editor-VolumeTextureToolkitEditor.exp
  @progress 'Compiling C++ source code...' 34%
  [12/35] TBRaymarchProject.init.gen.cpp
  @progress 'Compiling C++ source code...' 37%
  [13/35] TBRaymarchProject.cpp
  @progress 'Compiling C++ source code...' 40%
  [14/35] Module.RayUtils.cpp
  @progress 'Compiling C++ source code...' 43%
  [15/35] SharedPCH.Engine.ShadowErrors.Cpp17.cpp
  @progress 'Compiling C++ source code...' 46%
  [16/35] UE4Editor-RayUtils.lib
    ???ڴ????? D:\bishe\TBRaymarchProject-master\Plugins\Raymarcher\Intermediate\Build\Win64\UE4Editor\Development\RayUtils\UE4Editor-RayUtils.lib ?Ͷ??? D:\bishe\TBRaymarchProject-master\Plugins\Raymarcher\Intermediate\Build\Win64\UE4Editor\Development\RayUtils\UE4Editor-RayUtils.exp
  @progress 'Compiling C++ source code...' 49%
  [17/35] TBRaymarchProjectGameModeBase.cpp
  @progress 'Compiling C++ source code...' 51%
  [18/35] TBRaymarchProjectGameModeBase.gen.cpp
  @progress 'Compiling C++ source code...' 54%
  [19/35] UE4Editor-TBRaymarchProject.lib
    ???ڴ????? D:\bishe\TBRaymarchProject-master\Intermediate\Build\Win64\UE4Editor\Development\TBRaymarchProject\UE4Editor-TBRaymarchProject.lib ?Ͷ??? D:\bishe\TBRaymarchProject-master\Intermediate\Build\Win64\UE4Editor\Development\TBRaymarchProject\UE4Editor-TBRaymarchProject.exp
  @progress 'Compiling C++ source code...' 57%
  [20/35] Module.VolumeTextureToolkit.gen.cpp
  @progress 'Compiling C++ source code...' 60%
  [21/35] UE4Editor-RayUtils.dll
    ???ڴ????? D:\bishe\TBRaymarchProject-master\Plugins\Raymarcher\Intermediate\Build\Win64\UE4Editor\Development\RayUtils\UE4Editor-RayUtils.suppressed.lib ?Ͷ??? D:\bishe\TBRaymarchProject-master\Plugins\Raymarcher\Intermediate\Build\Win64\UE4Editor\Development\RayUtils\UE4Editor-RayUtils.suppressed.exp
  @progress 'Compiling C++ source code...' 63%
  [22/35] Module.Raymarcher.gen.cpp
  @progress 'Compiling C++ source code...' 66%
  [23/35] Module.FractalMarcher.cpp
  @progress 'Compiling C++ source code...' 69%
  [24/35] Module.FractalMarcher.gen.cpp
  @progress 'Compiling C++ source code...' 71%
  [25/35] UE4Editor-FractalMarcher.lib
    ???ڴ????? D:\bishe\TBRaymarchProject-master\Plugins\Raymarcher\Intermediate\Build\Win64\UE4Editor\Development\FractalMarcher\UE4Editor-FractalMarcher.lib ?Ͷ??? D:\bishe\TBRaymarchProject-master\Plugins\Raymarcher\Intermediate\Build\Win64\UE4Editor\Development\FractalMarcher\UE4Editor-FractalMarcher.exp
  @progress 'Compiling C++ source code...' 74%
  [26/35] Module.VolumeTextureToolkit.cpp
  @progress 'Compiling C++ source code...' 77%
  [27/35] UE4Editor-VolumeTextureToolkit.lib
    ???ڴ????? D:\bishe\TBRaymarchProject-master\Plugins\Raymarcher\Intermediate\Build\Win64\UE4Editor\Development\VolumeTextureToolkit\UE4Editor-VolumeTextureToolkit.lib ?Ͷ??? D:\bishe\TBRaymarchProject-master\Plugins\Raymarcher\Intermediate\Build\Win64\UE4Editor\Development\VolumeTextureToolkit\UE4Editor-VolumeTextureToolkit.exp
  @progress 'Compiling C++ source code...' 80%
  [28/35] Module.Raymarcher.cpp
  @progress 'Compiling C++ source code...' 83%
  [29/35] UE4Editor-Raymarcher.lib
    ???ڴ????? D:\bishe\TBRaymarchProject-master\Plugins\Raymarcher\Intermediate\Build\Win64\UE4Editor\Development\Raymarcher\UE4Editor-Raymarcher.lib ?Ͷ??? D:\bishe\TBRaymarchProject-master\Plugins\Raymarcher\Intermediate\Build\Win64\UE4Editor\Development\Raymarcher\UE4Editor-Raymarcher.exp
  @progress 'Compiling C++ source code...' 86%
  [30/35] UE4Editor-VolumeTextureToolkit.dll
    ???ڴ????? D:\bishe\TBRaymarchProject-master\Plugins\Raymarcher\Intermediate\Build\Win64\UE4Editor\Development\VolumeTextureToolkit\UE4Editor-VolumeTextureToolkit.suppressed.lib ?Ͷ??? D:\bishe\TBRaymarchProject-master\Plugins\Raymarcher\Intermediate\Build\Win64\UE4Editor\Development\VolumeTextureToolkit\UE4Editor-VolumeTextureToolkit.suppressed.exp
  @progress 'Compiling C++ source code...' 89%
  [31/35] UE4Editor-VolumeTextureToolkitEditor.dll
    ???ڴ????? D:\bishe\TBRaymarchProject-master\Plugins\Raymarcher\Intermediate\Build\Win64\UE4Editor\Development\VolumeTextureToolkitEditor\UE4Editor-VolumeTextureToolkitEditor.suppressed.lib ?Ͷ??? D:\bishe\TBRaymarchProject-master\Plugins\Raymarcher\Intermediate\Build\Win64\UE4Editor\Development\VolumeTextureToolkitEditor\UE4Editor-VolumeTextureToolkitEditor.suppressed.exp
  @progress 'Compiling C++ source code...' 91%
  [32/35] UE4Editor-TBRaymarchProject.dll
    ???ڴ????? D:\bishe\TBRaymarchProject-master\Intermediate\Build\Win64\UE4Editor\Development\TBRaymarchProject\UE4Editor-TBRaymarchProject.suppressed.lib ?Ͷ??? D:\bishe\TBRaymarchProject-master\Intermediate\Build\Win64\UE4Editor\Development\TBRaymarchProject\UE4Editor-TBRaymarchProject.suppressed.exp
  @progress 'Compiling C++ source code...' 94%
  [33/35] UE4Editor-FractalMarcher.dll
    ???ڴ????? D:\bishe\TBRaymarchProject-master\Plugins\Raymarcher\Intermediate\Build\Win64\UE4Editor\Development\FractalMarcher\UE4Editor-FractalMarcher.suppressed.lib ?Ͷ??? D:\bishe\TBRaymarchProject-master\Plugins\Raymarcher\Intermediate\Build\Win64\UE4Editor\Development\FractalMarcher\UE4Editor-FractalMarcher.suppressed.exp
  @progress 'Compiling C++ source code...' 97%
  [34/35] UE4Editor-Raymarcher.dll
    ???ڴ????? D:\bishe\TBRaymarchProject-master\Plugins\Raymarcher\Intermediate\Build\Win64\UE4Editor\Development\Raymarcher\UE4Editor-Raymarcher.suppressed.lib ?Ͷ??? D:\bishe\TBRaymarchProject-master\Plugins\Raymarcher\Intermediate\Build\Win64\UE4Editor\Development\Raymarcher\UE4Editor-Raymarcher.suppressed.exp
  @progress 'Compiling C++ source code...' 100%
  [35/35] TBRaymarchProjectEditor.target
Total time in Parallel executor: 49.24 seconds
Total execution time: 66.83 seconds
PIX capture plugin failed to initialize! Check that the process is launched from PIX.
MLSDK not found.  This likely means the MLSDK environment variable is not set.
Using libcurl 7.55.1-DEV
 - built for x86_64-pc-win32
 - supports SSL with OpenSSL/1.1.1
 - supports HTTP deflate (compression) using libz 1.2.8
 - other features:
     CURL_VERSION_SSL
     CURL_VERSION_LIBZ
     CURL_VERSION_IPV6
     CURL_VERSION_ASYNCHDNS
     CURL_VERSION_LARGEFILE
     CURL_VERSION_IDN
 CurlRequestOptions (configurable via config and command line):
 - bVerifyPeer = true  - Libcurl will verify peer certificate
 - bUseHttpProxy = false  - Libcurl will NOT use HTTP proxy
 - bDontReuseConnections = false  - Libcurl will reuse connections
 - MaxHostConnections = 16  - Libcurl will limit the number of connections to a host
 - LocalHostAddr = Default
 - BufferSize = 65536
OSS: Creating online subsystem instance for: NULL
WinSock: version 1.1 (2.2), MaxSocks=32767, MaxUdp=65467
OSS: TryLoadSubsystemAndSetDefault: Loaded subsystem for module [NULL]
Windows GetLastError: 操作成功完成。 (0)

**Comment by tommybazar** [comment]
From your log this is obviously an issue with "PIX capture plugin", not with my plugin.
