### ISSUE TITLE
DCM Import not working

### ISSUE THREAD

**Issue by RaulBM97** [tommybazar/TBRaymarcherPlugin#7]
When I'm trying to import a dcm file, the plugin doesn't load the dcm files. Even with mhd, the editor crashes. Any idea? Thank you.

**Comment by tommybazar** [comment]
Honestly, the DICOM loading is hacky as hell and I know for a fact it crashes with ~half of the DICOMs that I have on my system.

I need to integrate a proper DICOM loading library instead of a half-home-brew solution.
