### ISSUE TITLE
Issues migrating to v5.3

### ISSUE THREAD

**Issue by ezorfa** [tommybazar/TBRaymarcherPlugin#9]
Hey @tommybazar !

Thanks for the wonderful work!

While I was using this plugin in Unreal 5.3, I have this error:
`Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	C3248	'FRenderResource::InitDynamicRHI': function declared as 'final' cannot be overridden by 'FTexture3DComputeResource::InitDynamicRHI'	TBRaymarchProject	C:\Users\ezorfa\TBRaymarchProject-master\TBRaymarchProject-master\Plugins\TBRaymarcherPlugin\Source\VolumeTextureToolkit\Public\RenderTargetVolumeMipped.h	106		
`

Do you know why? and do you have the latest version yet?

**Comment by tommybazar** [comment]
Hi, currently working on the latest version. Seems Epic overhauled compute shader calls and assets a bit, so a lot is broken.
There is a 5.2 version up (in a branch of the same name).
